server:
  port: 8082

spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    dirver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gdut_service?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: '123456'
  resources:
    static-locations: classpath:/templates  #访问静态页面


mybatis:
  mapper-locations: classpath:mapper/*.xml